### PR TITLE
making config and callbacks not private

### PR DESCRIPTION
**Pull request by jiyoontbd**

### CODE REVIEW

**Review by diehuxx — APPROVED** [review]
Noice

**Review by diehuxx — COMMENTED** [review]
As I think more about, I'm not sure why we need to expose the callbacks. In fact, we should probably make them private in `tbdex-js`. We already have setters for the callbacks and "getting" a callback function is something I've never seen before. Not blocking, feel free to go ahead with what seems right to you.

**Review by KendallWeihe — APPROVED** [review]
2nd the points made by @diehuxx above

**Comment by jiyoontbd** [comment]
@diehuxx hmm... i think that deserves a bit of think. 

to maintain velocity, i am just gonna merge this for now, but added these tickets for future consideration

https://github.com/TBD54566975/tbdex-kt/issues/193
https://github.com/TBD54566975/tbdex-js/issues/195

**Pull request merged**
